apiVersion: apps/v1
kind: Deployment
metadata:
  name: player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player
  template:
    metadata:
      labels:
       app: player
    spec:
      containers:
      - name: player
        image: libertybikes-player
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: player
  labels:
    app: player
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30081
  selector:
    app: player
